### ISSUE TITLE
Feature Request: Selector for accessing width and height

### ISSUE THREAD

**Issue by xiavn** [bdmason/redux-window#1]
I thought it might be handy if there was an easy way to access the width and height properties reliably when mapping state to props or dispatching - like through a selector that could be imported. Obviously this may cause issues if the reducer was not initialised using the default settings - as the selector wouldn't work correctly. However it would also be useful if you ever decide to change the structure of the current state - for instance moving away from using w or h and instead using width or height; or if you added more functionality in the future.

**Comment by bdmason** [comment]
Width & height have been moved from w & h as you suggested I might! Selectors are now available through named exports `getWidth` and `getHeight`.
